[tool.black]
line-length = 78
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 78
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["PIL", "debug_toolbar", "django", "mixer", "pytest"]
