# Generated by Django 3.2.3 on 2021-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_group_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="О чём тут обычно пишут",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
