POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST http://localhost:8000/api/v1/token/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

GET http://localhost:8000/api/v1/group/
Content-Type: application/json

{}

###

GET http://localhost:8000/api/v1/group/1/
Content-Type: application/json

{}

###

POST http://localhost:8000/api/v1/group/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjIxMjM1OTQ1LCJqdGkiOiJmYTgyNjlkY2EwOWU0ZTQ3OTNhNTEzZjgyYmQ4YmViMiIsInVzZXJfaWQiOjN9.ySNey8ZCDCf7Dnxg9_0FornoeEND6o0e7greRuDRjxE
Content-Type: application/json

{
  "title": "Группа  номер 3"
}
